language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

dist: trusty

before_install:
  - sudo apt-get install -y libarchive13
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libarchive.so.13 /usr/lib/x86_64-linux-gnu/libarchive.so
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=libarchive
after_success:
  - coveralls
